### ISSUE TITLE
Documentation links are currently broken

### ISSUE THREAD

**Issue by Moobiful** [james7132/Hourai#19]
The [README.md](https://github.com/james7132/Hourai/blob/master/README.md) cites https://jamessliu.com/hourai/ for documentation when it should link https://jamessliu.com/Hourai/ instead.

**Comment by james5922** [comment]
Some links are still broken: https://jamessliu.com/wiki/modules/feeds/ throws a 404.

**Comment by james7132** [comment]
Main link fixed. Documentation is forthcoming.

**Comment by james7132** [comment]
This has been fixed with the new website implementation.
