### ISSUE TITLE
~queue/~nowplaying commands not working

### ISSUE THREAD

**Issue by Mudkip101004** [james7132/Hourai#37]
Upon deleting the message that pops up when you do ~queue or ~nowplaying, the respective command breaks and does not work anymore. Like, I used ~nowplaying, and then deleted the message that Hourai brought up, and ~nowplaying has ceased to work at all, even when kicking the bot and letting it back in. I tried the same with ~queue, using the command and deleting the message Hourai brought up, and again it became a broken command, which I thought was interesting, but I have not found a way to bring either back. ~stop also brings up an error message now whenever i use it, but the commands still functions as normal despite Hourai saying that there was an error.

**Comment by james7132** [comment]
This should be fixed. Can you confirm this?

**Comment by Mudkip101004** [comment]
Yes the commands have started working again! Thank you!
